#config_version=6
hardware:
    platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      cab:
        model: FP-I/O-0024
        order: 1
      3208: 
        model: FP-I/O-3208
        order: 2

    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  
switches:
  s_left_flipper:
    number: cab-8  # this can be blank if you don't have physical hw yet
  s_right_flipper:
    number: cab-16  # if you do have physical hw, most likely your number will be different

coils:
  c_flipper_left_main:
    number: 3208-3  # again, these numbers will probably be different for you
  c_flipper_left_hold:
    number: 3208-2  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    number: 3208-5
  c_flipper_right_hold:
    number: 3208-4
    allow_enable: true

playfields:
  playfield:
    tags: default
    default_source_device: None  # use None in steps before 8

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3